# See https://docs.aspect.build/v/workflows/config
tasks:
  - build:
      name: linux_amd64
      targets:
        - //:gazelle
      bazel:
        flags:
          - --platforms=@rules_go//go/toolchain:linux_amd64_cgo
  - build:
      name: linux_arm64
      targets:
        - //:gazelle
      bazel:
        flags:
          - --platforms=@rules_go//go/toolchain:linux_arm64_cgo
  - build:
      name: darwin_arm64
      targets:
        - //:gazelle
      bazel:
        flags:
          - --platforms=@rules_go//go/toolchain:darwin_arm64_cgo
  - build:
      name: windows_amd64
      targets:
        - //:gazelle
      bazel:
        flags:
          - --platforms=@rules_go//go/toolchain:windows_amd64_cgo
notifications:
  github: {}